# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define :backend do |backend|
		# backend.vm.box = "ubuntu/xenial64"
		backend.vm.box = "gbarbieru/xenial"
		backend.vm.network :private_network, ip:"192.168.56.102"
		backend.vm.hostname = "backend"
		backend.vm.provision "shell", inline: <<-SHELL
			echo "Hello world!" > input.txt
      		sudo apt-get update
      		sudo apt-get -y install nodejs-legacy
      		nohup node /vagrant/vm2_server.js 0<&- &>/dev/null &
    	SHELL
	end

	config.vm.define :frontend do |frontend|
		# frontend.vm.box = "ubuntu/xenial64"
		frontend.vm.box = "gbarbieru/xenial"
		frontend.vm.network :private_network, ip:"192.168.56.101"
		frontend.vm.hostname = "frontend"
		frontend.vm.network "forwarded_port", guest: 8888, host:8888
		frontend.vm.provision "shell", inline: <<-SHELL
      		sudo apt-get update
      		sudo apt-get -y install nodejs-legacy
      		nohup node /vagrant/vm1_server.js 0<&- &>/dev/null &
    	SHELL
  	end
end
